# ESPHome configuration for Word Clock v1 with German time display
# ESP8266-based word clock with addressable LED matrix via ESPHome

esphome:
  name: hw-test
  friendly_name: Hardware Test

esp8266:
  board: d1_mini  # Adjust to your ESP8266 variant (nodemcu, d1_mini, etc.)

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # ap:
  #   ssid: "WordClock-Fallback"
  #   password: !secret ap_password

captive_portal:

# Light output for addressable LED matrix
light:
  - platform: neopixelbus
    type: GRB
    pin: D4  # GPIO14 - Adjust to your pin
    num_leds: 121  # Adjust to your matrix size
    name: "LED Strip"
    id: ledstrip
    variant: WS2812
    